server:
  port: 8081
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://salmin.in/realms/teamgram
          jwk-set-uri: https://salmin.in/realms/teamgram/protocol/openid-connect/certs

teamgram:
  api:
    url: http://teamgram-server:8080

logging:
  level:
    org.springframework.security: DEBUG
    com.teamgram.admin: DEBUG
    org.springframework.web: DEBUG

cors:
  allowed-origins: https://admin.salmin.in
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type,Accept,Origin,X-Requested-With
  exposed-headers: Authorization
  allow-credentials: true
  max-age: 3600
