server:
  port: 8081
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://salmin.in/realms/teamgram
          jwk-set-uri: https://salmin.in/realms/teamgram/protocol/openid-connect/certs

teamgram:
  api:
    url: http://teamgram-server:8080

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    com.teamgram.admin: DEBUG
    reactor.netty.http.client: DEBUG

cors:
  allowed-origins: https://admin.salmin.in
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,HEAD
  allowed-headers: Authorization,Content-Type,Accept,Origin,X-Requested-With,Access-Control-Request-Method,Access-Control-Request-Headers
  exposed-headers: Authorization,Content-Disposition
  allow-credentials: true
  max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
