server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.salmin.in/realms/teamgram
          jwk-set-uri: https://auth.salmin.in/realms/teamgram/protocol/openid-connect/certs

teamgram:
  api:
    url: http://teamgram-server:8080

logging:
  level:
    org.springframework.security: DEBUG
    com.teamgram.admin: DEBUG

cors:
  allowed-origins: https://admin.salmin.in
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  exposed-headers: Authorization
  allow-credentials: true
  max-age: 3600
